version: "3.9"

services:
  mongo:
    image: mongo:6.0
    container_name: mongo_sales
    restart: unless-stopped
    ports:
      - "27017:27017"
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: sa
    #   MONGO_INITDB_ROOT_PASSWORD: oracle123
    #   MONGO_INITDB_DATABASE: salesdb
    volumes:
      - ./mongo/data:/data/db
