version: "3.9"

services:
  mongo:
    image: mongo:6.0
    container_name: mongo_sales
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - ./mongo/data:/data/db

  oracle:
    image: gvenzl/oracle-xe:21-slim
    container_name: oracle_dw
    restart: unless-stopped
    ports:
      - "1521:1521"
    environment:
      ORACLE_PASSWORD: oracle
      ORACLE_DATABASE: XEPDB1
      APP_USER: dw_user
      APP_USER_PASSWORD: dw_pass
    volumes:
      - ./oracle/data:/opt/oracle/oradata
